global using System;
global using System.Security.Cryptography;
global using System.Text;
global using Xunit;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using Zaabee.Cryptography.AES;
global using Zaabee.Extensions;